apiVersion: "v1"
kind: "Service"
metadata:
  name: "mlflow-server-service"
  labels:
    app: "mlflow-server-service"
spec:
  type: "LoadBalancer"
  selector:
    app: "mlflow-server"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8080
      targetPort: 5000
